[package]
name = "quant"
version = "0.1.0"
authors = ["spark"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
num = "0.3.0"
statrs = "0.12.0"
